[server]
# Add your Agent Token inside of the quotes in the line below
api_token = ""
submission_interval = "1s"

[data]
# path = 'c:\agent.sqlite3'
# WINDOWS USERS - Uncomment the line above and comment or remove the line below
path = "/tmp/agent.sqlite3"

[graphite]
listen_udp = ":2003"

[[flow]]
# Add the Flow Tag for the widget that you would like to update inside of the quotes below
tag = ""
interval = "2s"
# Add a path for a script that will generate JSON data inside of the quotes below
exec = ""
expiration = 0
