// generated by stringer -type=terminal; DO NOT EDIT

package parser

import "fmt"

const _terminal_name = "errorTerminaleofTerminalT_PLUST_MINUST_MULTIPLYT_DIVIDET_COLONT_DOTT_COMMAT_OPEN_PARENST_CLOSE_PARENST_OPEN_BRACKETT_CLOSE_BRACKETT_NUMBERT_STRINGT_IDENTIFIER"

var _terminal_index = [...]uint8{13, 24, 30, 37, 47, 55, 62, 67, 74, 87, 101, 115, 130, 138, 146, 158}

func (i terminal) String() string {
	i -= -2
	if i < 0 || i >= terminal(len(_terminal_index)) {
		return fmt.Sprintf("terminal(%d)", i+-2)
	}
	hi := _terminal_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _terminal_index[i-1]
	}
	return _terminal_name[lo:hi]
}
