listen: ":8000"
graphite:
    listen_tcp: ":2003"
    listen_udp: ":2004"
data:
    path: /tmp/agent.sqlite3
    ttl: 3600
jobs:
    - url: tpl://set_test_flow.asl
      flow_tag: test_flow
      expiration: 0
      refresh: 10