api_token: <Your API Key>
submission_interval: 1
jobs:
  - config:
      refresh: 10
      path: ./demo.php
      args:
        - value
        - 1320
      flow_tag: test_marco_1
      variant: value
      template:
        value: 123